<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZF2: Vacancies%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo "Vacancies list" /* TODO: translate*/ /*$this->translate('Follow Development')*/ ?></h3>
            </div>

            <div class="panel-body">
                <dl class="vacancy-list">
                    <?php
                    foreach ($this->vacancies as $vacancy) {
                        print '<dt>'
                            . $vacancy->getName()
                            . ' (' . $vacancy->getDepartment()->getName() . ')'
                            . '</dt>'
                            . '<dd>'
                            . $vacancy->getDescription()
                            . '</dd>';
                    }
                    ?>
                </dl>
            </div>
        </div>
    </div>
</div>
